services:
  - type: web
    name: esn-unipi-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://monkass:ESNUnipi@esnunipi.mhxfudu.mongodb.net/ESNUnipi
